"""remove payment event order foreign key

Revision ID: 4ff1bb3a9f29
Revises: a3f43427ff38
Create Date: 2026-09-03 15:39:44.254972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff1bb3a9f29'
down_revision: Union[str, Sequence[str], None] = 'a3f43427ff38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('payment_events_order_id_fkey'), 'payment_events', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('payment_events_order_id_fkey'), 'payment_events', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
