"""add provider keys

Revision ID: 63bd7aa3ffe2
Revises: 08d9805afc58
Create Date: 2026-09-03 19:04:25.033564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63bd7aa3ffe2'
down_revision: Union[str, Sequence[str], None] = '08d9805afc58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('available', 'issued', name='provider_key_status'), nullable=False),
    sa.Column('delivery_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_keys_code'), 'provider_keys', ['code'], unique=True)
    op.create_index(op.f('ix_provider_keys_delivery_id'), 'provider_keys', ['delivery_id'], unique=True)
    op.create_index(op.f('ix_provider_keys_status'), 'provider_keys', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_keys_status'), table_name='provider_keys')
    op.drop_index(op.f('ix_provider_keys_delivery_id'), table_name='provider_keys')
    op.drop_index(op.f('ix_provider_keys_code'), table_name='provider_keys')
    op.drop_table('provider_keys')
    # ### end Alembic commands ###
