"""add request id to provider keys

Revision ID: c34dbecc5e2f
Revises: 63bd7aa3ffe2
Create Date: 2026-09-04 21:03:24.973554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34dbecc5e2f'
down_revision: Union[str, Sequence[str], None] = '63bd7aa3ffe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_keys', sa.Column('request_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_provider_keys_request_id'), 'provider_keys', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_keys_request_id'), table_name='provider_keys')
    op.drop_column('provider_keys', 'request_id')
    # ### end Alembic commands ###
